version: '3.7'

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=patient_medical_records
      - MYSQL_USER=root
      - MYSQL_PASSWORD=supersecret
      - MYSQL_ROOT_PASSWORD=supersecret
    command: --default-authentication-plugin=mysql_native_password

volumes:
    mysql_data: